on:
  push:
    branches:
      - main
      - build-deploy

name: Build and Release Apps
jobs:
  build:
    name: Build Apps
    runs-on: ubuntu-latest
    # runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Setup Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install Ruby Dependencies
        run: cd android && bundle install
      - name: Create Secrets
        run: |
          echo "$GOOGLE_SERVICES" >> android/app/google-services.json
        shell: bash
        env:
          GOOGLE_SERVICES : ${{secrets.GOOGLE_SERVICES}}
      - name: Fastlane Build & Release
        run: |
          cd android &&
          bundle exec fastlane alpha


