on:
  push:
    branches:
      - main
      - build-deploy

name: Build and Release Apps
jobs:
  build:
    name: Build Apps
    runs-on: ubuntu-latest
    # runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup Java 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Setup Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install Ruby Dependencies
        working-directory: ./android
        run: bundle install
      - name: Create Secrets
        run: |
          echo "$GOOGLE_SERVICES" >> android/app/google-services.json
          echo "$KEY_PROPERTIES" >> android/key.properties
          mkdir -p keys/android
        shell: bash
        env:
          GOOGLE_SERVICES: ${{secrets.GOOGLE_SERVICES}}
          KEY_PROPERTIES: ${{secrets.KEY_PROPERTIES}}
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keys/android/upload-keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - name: Check Files
        working-directory: ./keys/android
        run: |
          ls .
        shell: bash
      - name: Fastlane Build & Release
        working-directory: ./android
        run: bundle exec fastlane alpha


